project_id = "ucptoyqlsysnxfjgqttq"

[db]
major_version = 17

[api]
enabled = true
schemas = ["public"]

[auth]
enabled = true

[auth.email]
enable_signup = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
